name: Build and test dbuf

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            name: "Windows (VS 2022, Release)"
            generator: "Visual Studio 17 2022"
            c-compiler: "cl"
            cxx-compiler: "cl"

          - os: ubuntu-latest
            name: "Linux (Clang, Release)"
            generator: Ninja
            c-compiler: "clang-21"
            cxx-compiler: "clang++-21"

          - os: macos-latest
            name: "macOS (Clang, Release)"
            generator: Ninja
            c-compiler: "clang"
            cxx-compiler: "clang++"

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Ninja + Clang 21
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build wget lsb-release software-properties-common gnupg

          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21 all

      - name: Configure & Build
        uses: threeal/cmake-action@v2.1.0
        with:
          generator: ${{ matrix.generator }}
          c-compiler: ${{ matrix.c-compiler }}
          cxx-compiler: ${{ matrix.cxx-compiler }}
          options: |
            CMAKE_BUILD_TYPE=Release
            DBUF_BUILD_TESTS=ON
          build-args: --config Release --parallel

      - name: Run tests
        run: ctest --test-dir build --output-on-failure -C Release
